### ISSUE TITLE
beamer dependencies not fulfilled anymore

### ISSUE THREAD

**Issue by letzfets** [ho-tex/ltxcmds#1]
ltxcmds seems to have disappeared this morning (2019-12-17, 6.34).
Beamer depends on atbegshi.sty, which requires "ltxcmds".
In my TeX Liive utility update on MaC, ltxcmds disappeared this morning, which broke my dependency chain to compile beamer. Can you please fix ASAP? Thx

**Comment by davidcarlisle** [comment]
Like several other packages it is now in its own directory on ctan not under oberdiek, but it is there

https://ctan.org/tex-archive/macros/latex/contrib/ltxcmds

We have no control over distribution onward from ctan, I suggest that you update your miktex or texlive to force `ltxcmds` to update (it may be that some mirrors have not fully synchronised yet with the main ctan host

**Comment by letzfets** [comment]
Thank you,

I reverted to the old "oberdiek" package (as well as "atbegshi",
"infwarrer" & "hyperref"). The only reason, why I couldn't figure it out
myself for "ltxcmds" was, that the package changed name recently from
"oberdiek". Thanks for the fast help David!

Cheers and Merry Christmas!


Den tir. 17. dec. 2019 kl. 11.27 skrev David Carlisle <
notifications@github.com>:
