### ISSUE TITLE
version (date) format

### ISSUE THREAD

**Issue by tsouanas** [ho-tex/ltxcmds#4]
After upgrading my texlive to 2021 I noticed that my main project broke and it seems that the change in date/version format of ltxcmds.sty is what caused it.

With the actual `ltxcmds.sty` I get:
```
! Missing = inserted for \ifnum.
<to be read again> 
                   -
<argument> 2020-
                05-10 v1.25 LaTeX kernel commands for general use (HO)
\@parse@version #1/#2/#3#4#5\@nil ->#1
                                      #2#3#4 
\@ifl@t@r ...andafter \@parse@version #1//00\@nil 
                                                  <\expandafter \@parse@vers...

\eplain@pr@videpackage ...fl@t@r {#2}\usepkg@date 
                                                  {}{\message {Warning: you ...

\x #1#2[#3]->\endgroup #2[{#3}]
                               \ifx #1\@undefined \xdef #1{#3}\fi \ifx #1\re...
l.111 ...TeX kernel commands for general use (HO)]
                                                  %
? x
No pages of output.
```
Simply changing those `-` to `/` "solves the problem" but I suppose the was a reason why the format of this date/version changed and I also suppose that projects using `ltxcmds.sty` were not supposed to break with such change in the manner mentioned above.
Any help with this would be greatly appreciated; for the time being I'm keeping a local modified copy of `ltxcmds.sty` to override the original one, the only change being the one I mentioned above.

**Comment by davidcarlisle** [comment]
Please provide a test file that shows any issue.

LaTeX has supported yyyy-mm-dd date format since 2017, keeping / also working for legacy compatibility. That change is in the format not specific to this package,

from

```
\documentclass{article}

\usepackage{ltxcmds}

\listfiles

\begin{document}

x
\end{document}
```

I get

```
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-04-10>
...
 *File List*
 article.cls    2021/10/04 v1.4n Standard LaTeX document class
  size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
 ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
l3backend-pdftex.def    2022-04-14 L3 backend support: PDF output (pdfTeX)
 ***********
```

so the format itself, the the L3 programming layer and ltxcmds are using `-` just `article` and `size10.clo` using the legacy / format

**Comment by tsouanas** [comment]
Thanks for the prompt reply and for the explanation!  I'm using plain TeX (the project that broke is using eplain.tex), compiling with `xetex`.  Turns out I was using an old version of eplain that was only parsing the "old" format.  I updated it and it works.  Thanks again, I hadn't noticed the change in the format.
